Display entered word on typo
r3oath/burst-type.pro pull request #87
Opened 2024-02-15 05:40 UTC by rwz

When typo occurs, display entered word back at user. Feel free to reject, this is a super low-effort PR mainly made to scratch my own itch.

2024-02-15 05:59 UTC, rwz commented
I wish there was a way to see what Vercel build is complaining about without registering for an account. I don't use TypeScript normally, so maybe my code is horribly broken, but it seems to work on the local dev server.

Not sure what's happening here.

2024-02-15 09:18 UTC, r3oath commented
I'll take a look and see what's going wrong on the Vercel side.

2024-02-15 09:35 UTC, r3oath requested changes

2024-02-15 09:35 UTC, r3oath commented on components/word-visualiser.tsx
> +			return output;
This doesn't follow the code style conventions; you'll need to add the missing braces on the if statement, add in the correct newline separators, and use strict equality checks:

```suggestion
			let output = 'Typo';

			if (state.typoText !== undefined && state.typoText !== ' ') {
				output += `: ${state.typoText}`;
			}

			return output;
```

2024-02-15 09:35 UTC, r3oath commented on components/word-visualiser.tsx
> +			return output;
`state.typoText` is also missing from the `useMemo` dependency array below.

2024-02-16 04:07 UTC, rwz commented
Oh, I've discovered that I could run `npm run lint` and see what it doesn't like about my code. Also Vercel won't show details even to people with accounts, unless they belong to the right group, which seems unfortunate.

Anyways, current version seem to be passing.

2024-02-16 04:58 UTC, r3oath commented
Yeah, that's expected; otherwise, I'd have to set up and pay for a Pro team account on Vercel. But everything should pass as long as you can run `npm run build` and `npm run lint` locally with no issues. If anything else is failing on the Vercel side, it's something that I would need to rectify personally.

Anyway, that's all looking good. I'll merge this in. Thanks for the contributions 👍

2024-02-16 04:58 UTC, r3oath approved these changes

2024-02-16 05:00 UTC, merged